### PR TITLE
Make first-heading-level configurable

### PR DESCRIPTION
**Pull request by michaelmior**
It would be nice if an option could be provided to the `first-heading-level` rule to set it to something other than 1. I have a case where all my Markdown files should start at level 2 instead.

### CODE REVIEW

**Comment by michaelmior** [comment]
Updated both rules to allow specification of the heading level.

**Comment by wooorm** [comment]
:+1: merging!

**Comment by wooorm** [comment]
I’ll release this once travis completes.

**Comment by wooorm** [comment]
Released in 3.1.0!

**Comment by michaelmior** [comment]
Awesome! Thanks :)

**Comment by wooorm** [comment]
:+1:

**Pull request closed without merging**
