### PR TITLE
make `list-item-spacing`'s message more clear

### LINKED ISSUE #60: Clarify `list-item-spacing` message
It seems there is no way to satisfy both rules for lists with long lines of am I mistaken?

### PR DESCRIPTION
**Pull request by despairblue**
fix #60

### CODE REVIEW

**Comment by wooorm** [comment]
Looks clean, simple, and good! Was there anything you struggled with, or other suggestions for this project?

**Comment by despairblue** [comment]
Nope. [Your comment](https://github.com/wooorm/remark-lint/issues/60#issuecomment-215092898) told me what rule is responsible for that test. After that it was just

1. finding the correct file (easy because the file names are the rule names)
2. finding the the part that creates the warning
3. understanding a little bit more about the file (very clean, understandable code 👍 )
4. changing the output.

So maybe the linter could prepend error/warning with the rule's name (like eslint does). I'm not sure if it already does that in a terminal, I only interacted with it through Atom.

**Comment by wooorm** [comment]
Great, thanks for the feedback!

What you’re talking about is called a `ruleId` (both in ESLint and in VFile’s, which are used here), and those are populated by the [main remark-lint library](https://github.com/wooorm/remark-lint/blob/master/lib/index.js#L108). The standard [reporter](https://github.com/wooorm/vfile-reporter) displays those at the end of a message.

As you’re using Atom, displaying the `ruleId` should be enabled in that library. If you’re using [`linter-markdown`](https://github.com/AtomLinter/linter-markdown), it [*should* be supported already](https://github.com/AtomLinter/linter-markdown/blob/9ff3ccd85db2adbc9f2873be16b4c533ba38e392/lib/index.js#L70), though. If not, please raise an issue. Or, if using another library, raise an issue over there.

Does that help?

**Comment by despairblue** [comment]
You're right, I must have overseen it. My bad. Then everything is alright from my side.

**Comment by despairblue** [comment]
On another note, why is it necessary that lists containing wrapped items must be loose? That adds a `p` and `br` tags to each item in that list and thus changes the rendering, at least the github renderer does it.

This seems to make it impossible to have a free flowing list item while still adhering to the 80 character line limit.
## Example

-   Wrapped item Dolor quas fugiat saepe qui. Aperiam eveniet autem ab et ab
    temporibus vero quo. Dolor quas fugiat saepe qui. Aperiam eveniet autem ab
    et ab temporibus vero quo.

-   item 2

-   item 3

----

-   Wrapped item Dolor quas fugiat saepe qui. Aperiam eveniet autem ab et ab
    temporibus vero quo. Dolor quas fugiat saepe qui. Aperiam eveniet autem ab
    et ab temporibus vero quo.
-   item 2
-   item 3

**Comment by wooorm** [comment]
Yes, that’s right. It’s from the [markdown-style-guide](http://www.cirosantilli.com/markdown-style-guide/#empty-lines-inside-lists), which is the source of inspiration and rules for this library. I personally prefer it too, as it makes reading the source easier, although indeed rendering on GitHub is less beautiful.

Note that you can always turn it off!

**Comment by wooorm** [comment]
Thanks @despairblue for working on this! 👍

**Pull request closed without merging**
