### PR TITLE
Look up global packages when the executable is global

### LINKED ISSUE #38: If remark is global, remark-lint should look up globally too
Spin off from https://github.com/chcokr/remark-lint-sentence-newline/issues/19

I'll send in a PR in a couple of days...

### PR DESCRIPTION
**Pull request by chcokr**
Fixes #38

### CODE REVIEW

**Comment by chcokr** [comment]
Passes `npm run lint` and `npm test` now.

Questions:
- Should I add any documentation elsewhere?
- Should I add any tests?

**Comment by chcokr** [comment]
Noticed something strange.

When I run the following command (which is the whole point of this whole PR for me):

```
remark --no-stdout -u remark-lint="external:[\"remark-lint-sentence-newline\"]" readme.md
```

Before I issue an `npm run build`, the command works as this PR intends.

But after an `npm run build`, the following error occurs:

```
readme.md
        1:1  error    TypeError: Cannot read property 'prefix' of null
    at module.exports (/Users/chcokr/code/remark-lint/remark-lint.js:6688:37)
    at Object.3../filter (/Users/chcokr/code/remark-lint/remark-lint.js:181:38)
    at s (/Users/chcokr/code/remark-lint/remark-lint.js:1:686)
    at /Users/chcokr/code/remark-lint/remark-lint.js:1:737
    at Object.1../lib (/Users/chcokr/code/remark-lint/remark-lint.js:14:18)
    at s (/Users/chcokr/code/remark-lint/remark-lint.js:1:686)
    at e (/Users/chcokr/code/remark-lint/remark-lint.js:1:857)
    at /Users/chcokr/code/remark-lint/remark-lint.js:1:875
    at a (/Users/chcokr/code/remark-lint/remark-lint.js:1:150)
    at Object.<anonymous> (/Users/chcokr/code/remark-lint/remark-lint.js:1:388)
```

So it looks like something's going wrong as we switch over from executing directly from `index.js` to running from the bundled `remark-lint.js`. Do you happen to know what's going wrong?

**Comment by wooorm** [comment]
By any chance, do you have remark, remark-lint, or the rule `npm link`ed?

**Comment by chcokr** [comment]
I have remark-lint `linke`ed.

**Comment by wooorm** [comment]
Also suggest mentioning that global rules work with global remark-lint and remark, [somewhere here](https://github.com/wooorm/remark-lint/blob/master/script/additional.json).

**Comment by chcokr** [comment]
(going to bed, be back tomorrow)

**Comment by wooorm** [comment]
:sleeping: I’ll test this out though!

**Comment by wooorm** [comment]
@chcokr P.S., I’m getting a warning for your valid example from the [readme](https://github.com/chcokr/remark-lint-sentence-newline#remark-lint-sentence-newline):

```md
<!-- Invalid -->

Hello, world. This sentence should be on a second line.

<!-- Valid -->

Hello, world.
This sentence should be on a second line.

Hello.<-There is no space after the dot, so this is not an error.

"Hello, world!" This sentence is not required to be on a second line because
!" is not an end of sentence.
! is, but not !".
But you're free to add a newline after !", or wherever.
This rule's job is to complain when you *don't* have a newline in certain cases.
It never complains when you do have a newline.
```

Yields:

```txt
example.md
       3:13  warning  Newline should follow end of sentence  sentence-newline
       14:1  warning  Newline should follow end of sentence  sentence-newline
```

**Comment by wooorm** [comment]
The problem you see in https://github.com/wooorm/remark-lint/pull/39#issuecomment-171146939 is because there’s, after an `npm run build`, `remark-lint` file in the `remark-lint` directory.

Currently, files are given precedence over packages in `node_modules/`. I may change that in the future, but at least it’s a separate issue from this :)

**Pull request closed without merging**
